const dict={
en:{navHome:"Home",navAbout:"About",navSkills:"Skills",navProjects:"Projects",navContact:"Contact",status:"Junior Developer",hello:"Mohammed",role:"Frontend Developer | Backend Explorer",heroText:"I'm a high school graduate, passionate about building web applications and turning ideas into real projects. I'm still learning, improving, and working on projects that will make a difference — one commit at a time.",projectsBtn:"View My Projects",cvBtn:"Download CV",aboutTitle:"About Me",aboutText:"I'm Mohammed Amas, a high school graduate and junior developer with a passion for web development. I mainly focus on frontend development, but I also have experience with backend technologies and enjoy working on both sides of the stack.",aboutText2:"I'm currently working on several personal projects, learning new technologies, and building my skills to become a better developer every day.",moreAbout:"More About Me",education:"Education",focus:"Focus",location:"Location",statLabel:"Status",statValue:"Learning & Building",skillsTitle:"Skills",tools:"Tools & Others",learning:"Currently Learning",projectsTitle:"Projects",projectsIntro:"Here are some of the projects I'm currently working on. They're still in development, but I'm making steady progress!",viewAll:"View All Projects →",p1:"Portfolio Website",p2:"Chat App",p3:"Todo App",p4:"Weather App",p1Text:"A personal portfolio website to showcase my skills, projects, and journey as a developer.",p2Text:"A real-time chat application with user authentication and live messaging.",p3Text:"A simple and clean todo application with local storage and categories.",p4Text:"Get real-time weather data with a clean and responsive UI.",contactTitle:"Let's Connect",contactHeadline:"Let's build something useful.",contactText:"Follow my work or reach out through the social platforms below.",rights:"All rights reserved.",coffee:"Built with ♥ and a lot of caffeine ☕"},
ar:{navHome:"الرئيسية",navAbout:"عني",navSkills:"المهارات",navProjects:"المشاريع",navContact:"تواصل",status:"مطور مبتدئ",hello:"محمد",role:"مطور واجهات أمامية | مستكشف للخلفية",heroText:"أنا خريج ثانوية شغوف ببناء تطبيقات الويب وتحويل الأفكار إلى مشاريع حقيقية. ما زلت أتعلم وأتطور وأعمل على مشاريع تصنع فرقاً — عملية برمجية بعد أخرى.",projectsBtn:"شاهد مشاريعي",cvBtn:"تحميل السيرة",aboutTitle:"عني",aboutText:"أنا محمد أماس، خريج ثانوية ومطور مبتدئ شغوف بتطوير الويب. أركز بشكل أساسي على الواجهات الأمامية، ولدي أيضاً خبرة في تقنيات الخلفية وأستمتع بالعمل على جانبي التطبيق.",aboutText2:"أعمل حالياً على عدة مشاريع شخصية، وأتعلم تقنيات جديدة، وأطوّر مهاراتي لأصبح مطوراً أفضل كل يوم.",moreAbout:"المزيد عني",education:"التعليم",focus:"التركيز",location:"الموقع",statLabel:"الحالة",statValue:"أتعلّم وأبني",skillsTitle:"المهارات",tools:"الأدوات وغيرها",learning:"أتعلم حالياً",projectsTitle:"المشاريع",projectsIntro:"هذه بعض المشاريع التي أعمل عليها حالياً. ما زالت قيد التطوير، لكنني أتقدم بثبات!",viewAll:"عرض كل المشاريع →",p1:"موقع شخصي",p2:"تطبيق محادثة",p3:"تطبيق مهام",p4:"تطبيق الطقس",p1Text:"موقع شخصي لعرض مهاراتي ومشاريعي ورحلتي كمطور.",p2Text:"تطبيق محادثة فوري مع تسجيل المستخدمين والرسائل المباشرة.",p3Text:"تطبيق مهام بسيط ومنظم مع التخزين المحلي والتصنيفات.",p4Text:"الحصول على بيانات الطقس المباشرة بواجهة نظيفة ومتجاوبة.",contactTitle:"لنبقَ على تواصل",contactHeadline:"لنبنِ شيئاً مفيداً.",contactText:"تابع أعمالي أو تواصل معي عبر المنصات الاجتماعية أدناه.",rights:"جميع الحقوق محفوظة.",coffee:"بُني بالحب ♥ والكثير من القهوة ☕"}};
let lang=localStorage.getItem("portfolio-lang")||"en";
const root=document.documentElement;
function applyLang(){root.lang=lang;root.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=dict[lang][el.dataset.i18n];if(value)el.textContent=value});document.getElementById('langBtn').innerHTML=lang==='en'?'EN <span>عربي</span>':'AR <span>English</span>';document.title=lang==='en'?'Mohammed Amas — Developer Portfolio':'محمد أماس — ملف المطور';}
function applyTheme(){const light=localStorage.getItem('portfolio-theme')==='light';document.body.classList.toggle('light',light);document.getElementById('themeBtn').textContent=light?'☾':'☼';}
document.getElementById('langBtn').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('portfolio-lang',lang);applyLang()});
document.getElementById('themeBtn').addEventListener('click',()=>{localStorage.setItem('portfolio-theme',document.body.classList.contains('light')?'dark':'light');applyTheme()});
document.getElementById('menuBtn').addEventListener('click',()=>document.body.classList.toggle('mobile-open'));
document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('mobile-open')));
document.getElementById('year').textContent=new Date().getFullYear();
applyLang();applyTheme();
